name: bench_test_buddies
description: A new Flutter application.



publish_to: 'none'











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0
  provider: 4.3.2+2
  firebase_auth: ^0.18.4
  better_player:
  google_sign_in: ^4.5.6
  pin_code_text_field: 1.7.1
  carousel_pro: 1.0.0
  intro_views_flutter: ^2.8.2
  intl:
  flutter_circular_chart: ^0.1.0
  dio:
  simple_timer: ^1.0.1
  file_picker:
  http: 0.12.2
  async:

  image_picker:
  flutter_absolute_path: ^1.0.6
  path_provider:



  flutter_time_picker_spinner: ^1.0.6+1
  im_stepper: ^0.1.2+10
  bench_test_service:

    path: ./bench_test_service


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/on_boarding_images/
    - assets/on_boarding_images/3.0x/
    - assets/on_boarding_images/2.0x/
    - assets/Home_page_images/
    - assets/attempt_images/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF Pro Text/FontsFree-Net-SFProText-Bold.ttf
          weight: 800
        - asset: assets/fonts/SF Pro Text/FontsFree-Net-SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF Pro Text/FontsFree-Net-SFProText-Medium-1.ttf
          weight: 500
        - asset: assets/fonts/SF Pro Text/FontsFree-Net-SFProText-Regular-1.ttf
          weight: 300

  
  
