import 'package:bench_test_service/bench_test_service.dart';
import 'package:bench_test_service/model/request/store_attempt_request.dart';
import 'package:bench_test_service/model/request/store_evaluation_request.dart';
import 'package:bench_test_service/model/response/countries.dart';
import 'package:bench_test_service/model/response/exercise_evaluation_response.dart';
import 'package:bench_test_service/model/response/get_user_response.dart';
import 'package:bench_test_service/model/response/response_exercise.dart';
import 'package:bench_test_service/model/response/signup_question_response.dart';
import 'package:bench_test_service/model/response/store_evaluation_response.dart';
import 'package:bench_test_service/service/exercise.dart';
import 'package:dio/dio.dart';

void main() async {
  String token =
      // 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDQ2NmJmOTE3YjFjMjcwMTRlNjVkYzE3NzM3YjJjYWY5OWQ0MDIwYWI2ODdkODQwNmJlMDIyYjQ5MjA5MzE2OTAwMjNkZGM0NzNhYjY2NzAiLCJpYXQiOjE2MDgzNzUwMTYsIm5iZiI6MTYwODM3NTAxNiwiZXhwIjoxNjM5OTExMDE2LCJzdWIiOiIzNDIiLCJzY29wZXMiOltdfQ.vwLMuaFSEljuvyu1S0ya57lQb2YDrO5xhvOAC6keF49yQwIzhpQ_lp7F0_XsKrfOaffdIn8OKkR4eFofh5hrCkMfbCgXBhxyqvwonu62WWMhFqM0xMZs4u9L6iUcJGekxKTJvnnQ_9V_4mB4_oF4qHT0Y9hPu3LfTW5oYcyN-lcOmfeGZktWIqPOonEWK00YvudfzYx9mBUbiGWMmpqsXRc80gyvW5lJFgICMuxdvD5JUQTsuh_yPRK5Ve73puhiJJ9MDVF0HYqKtoe6_d0NyfZPwIKP-8Ftx1tZPsg-Vccdk4lBDfFZUPOuUnULuSRkK-QUfgcW7BpXNV5Gcp5Pkmbq-u0IfOArKT1efi1qCqkntKEtKYIONIQgE5w1ReyovnPwZROR-usceDRJLDZ4qTY7tGv6mNQHHeaDgbELo9UTYas38AWDZeXpa0hGUCUSYpn_dgUHBbxDzsiCKSOF99rfh5jiaHBzTF6UXcNHA-LcmAfKwXtHKw9Lp0AfkH6qpc2V4Jb0jdGe_Vb9465FaaG0rjrHDh5E2pOar5ofYX-VdXLa0r-hrBIZAqOJE8L2QSJHSGflTMLAUDprBHgaBa0xqPZFT8DR4O7ZgE-WMEmArWV0oE_Fb7bJWYNg_4BM8xFCDuLhv2Xk9LKe8JGv8iU7DgI4tdrwgcxMJC4KJrE';
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGIxOWVjMjRhMDAzZDU0NmFiMWQ3ZjhlYjgyZmJlMDAzZDFmNDU2OTRkNWIyZDhkNzU2M2UwYmZhZWYyZjdlNjUxZGYzZTE2NzlhZGU0MmEiLCJpYXQiOjE2MTAyODg3MjIsIm5iZiI6MTYxMDI4ODcyMiwiZXhwIjoxNjQxODI0NzIyLCJzdWIiOiIzNDIiLCJzY29wZXMiOltdfQ.qeSeDId_n6NbHBWryP7_YP4QzFc5M_WNSLPs9g9niu7FzJr6o0wNotRbSwiXMGkQHHPc2WV3-NLLqU8CTd61IeZrgvJ0XThQqJeUhp5V5_Wk1UNmD3gVkjqvMYospZNQhhuBrv2wy0VTk2Zj1RFjQQpbLc4RE6An1snWZeTbzkV17XkcLo9Y6cRBjMHu0UMwzi4WQHyJ-fZh3auU-QwUp4jhGddz9BjavZkfIlkIhedNW2Ky2XrJnHbY2Xgn7qPU1lTvPU8iuut_67sAhw1cqo9bn9mFvxqy810g40UjJEc1F9YeWz6Fd6zH4iTxwUyVvxo5wD98Zk9IWPg7Y9blCFcZlEChkAaiTp0Fbcd2JIbXdEByXqbRDN70d_ePfYoY7lNcDXMuOAlEaV48FJ3Q1IjsiCzyRLDXZLF70SOsIGLPGXxr4IasgTjB1S8IBAh0rt1X5LKaRuSAEiJCjOujvv0x75FBtLuZhD5ZVqCAxI0KrkEoy1Z3cZpEZbRAEoWDh7mvp44GunAwSdsOZdy2QMoYl_XL1WxtItfR2egrcTxiFNz7YX_ZQ3EvO0ljgVbRWRmHiw_sAOfpe2j3WK8oD6Ss-ayFy-cpXf2rS4Pxrke6w06B6_3z6Y2fgTBKODFzWZ4rg_vnXsUbHENM_WlW5QF6lLSKfVLIVoUQHn30KHE";
  try {
    var response = await Exercise().getAttempts(5, token);
    print(response);
  } on ErrorResponse catch (err) {
    print('Error:');
    print(err.toJson());
  }
}
